### ISSUE TITLE
send class adds extension to file name

### ISSUE THREAD

**Issue by mhmd1983** [robsonvleite/uploader#18]
Hi
I'm using this code to upload 
`    $fileUploader = new CoffeeCode\Uploader\Send("data/torrents", "torrent_files", ["application/x-bittorrent"],["torrent"],FALSE);
$Torrent['filename'] = $fileUploader->upload($_FILES['torrent'], $TorrentID . ".torrent");
`
the uploaded file name looks like this 1000-torrent.torrent
I want it to be 1000.torrent , how to fix this ?

**Comment by robsonvleite** [comment]
Hey @mhmd1983 , você pode ver o exemplo em https://github.com/robsonvleite/uploader/blob/master/example/send.php
