### ISSUE TITLE
Aviso de arquivo não suportado

### ISSUE THREAD

**Issue by ketterreis** [robsonvleite/uploader#3]
[ Linha 117 ] exif_read_data(phpD847.tmp): File not supported
C:\xampp\htdocs\fsphp\07-recursos-e-componentes\vendor\coffeecode\uploader\src\Image.php

A classe suporta o arquivo png, tanto é que o arquivo é carregado na pasta corretamente, contudo ao testar diversos arquivos desta extensão é disparado o aviso citado acima conforme imagem:
![image](https://user-images.githubusercontent.com/10655680/60734253-bc1af380-9f25-11e9-8ecd-c5e8398085a7.png).

O mesmo erro não ocorre para arquivos (.jpg e .gif).

**Comment by meleu** [comment]
confirmo o mesmo problema ocorrendo comigo.

**Comment by josineiaraujo** [comment]
Está acontecendo a mesma coisa comigo.

**Comment by josineiaraujo** [comment]
#7 
Pesquisando eu descobri que 'exif_read_data' funciona apenas com os tipos JPEG e TIFF, como diz o manual do php: https://www.php.net/manual/en/function.exif-read-data.php . Esta correção faz com que a função checkAngle, que usa ou 'exif_read_data' não seja chamada para arquivos PNG. Fiz um pool request #7 .

**Comment by robsonvleite** [comment]
O pull de correção foi aceito. Vamoooo!
