### ISSUE TITLE
Erro upload jpeg arquivo baixo da Net.

### ISSUE THREAD

**Issue by ghost** [robsonvleite/uploader#6]
Baixei uma série de arquivos para upload da net. De uma séria de 10 em 3 ocorreram esse erro: Warning: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x89 0x50 in /Applications/XAMPP/xamppfiles/htdocs/XXXXXXXXXX/vendor/coffeecode/uploader/src/Image.php on line 62.  Verificando o arquivo ele não abre no Photoshop. Teria como verificar e não quebrar o código no retorno? Ele gera o erro e no final retorna a string com o endereço do upload e salva um registro no banco de dados porém sem a imagem.

**Comment by robsonvleite** [comment]
Fala meu velho, tu consegue tratar os erros na aplicação usando try catch e testando o upload. De fato existem alguns arquivos com DRM que não podem ser enviados.
