### ISSUE TITLE
Imagen png não comprime

### ISSUE THREAD

**Issue by mauriciosantosds** [robsonvleite/uploader#8]
As imagens em png estão ficando maiores que as imagens png originais.

**Comment by robsonvleite** [comment]
Fala meu velho, PNG é por compreensão já o jpg é por % de qualidade.

Ex: PNG = comprime X 5
JPG = qualidade 70%

**Comment by robsonvleite** [comment]
IMPORTANTE: O PNG leva a compressão de 0-9, onde 9 tem um custo bem alto de processamento.
